apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    job: results
    app: results
spec:
  selector:
    app: results
  ports:
    - name: web
      port: 8085
      protocol: TCP
      targetPort: 8085
      nodePort: 30005
  type: NodePort