apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: results
  template:
    metadata:
      labels:
        app: results
    spec:
      containers:
      - name: voting
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
          - containerPort: 8085
        env:
          - name: VOTING_SERVICE_URL
            value: "http://localhost:30004"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "Omowunmi28"
          - name: POSTGRES_DB
            value: "postgres"